### ISSUE TITLE
null value in column "campaign" violates not-null constraint

### ISSUE THREAD

**Issue by mhurne** [yegor256/mailanes#25]
I attempted to subscribe to the monthly summary e-mails at https://www.yegor256.com/about-me.html#form but was taken to the error below upon clicking the Subscribe button. Note that despite the error in the browser, I did receive an e-mail indicating I was successfully subscribed.

> Internal error at 0.0.0
> 
> Please help us improve our service and submit the following stacktrace to our issue tracker in GitHub: yegor256/0pdd

    ERROR:  null value in column "campaign" violates not-null constraint
    DETAIL:  Failing row contains (15186, 13250, null, null, Subscribed., 2018-09-05 14:20:27.848728, null).

	/app/objects/pgsql.rb:40:in `async_exec_params'
	/app/objects/pgsql.rb:40:in `block in exec'
	/app/objects/pgsql.rb:39:in `synchronize'
	/app/objects/pgsql.rb:39:in `exec'
	/app/objects/recipient.rb:94:in `post_event'
	/app/mailanes.rb:432:in `block in <top (required)>'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1635:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1635:in `block in compile!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1011:in `route_eval'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1040:in `block in process_route'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1038:in `catch'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1038:in `process_route'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:990:in `block in route!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:989:in `each'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:989:in `route!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1097:in `block in dispatch!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `block in invoke'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `catch'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `invoke'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1094:in `dispatch!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:924:in `block in call!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `block in invoke'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `catch'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `invoke'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:924:in `call!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:913:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-ssl-1.4.1/lib/rack/ssl.rb:27:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.3/lib/rack/protection/xss_header.rb:18:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.3/lib/rack/protection/json_csrf.rb:26:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.3/lib/rack/protection/base.rb:50:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.3/lib/rack/protection/base.rb:50:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.3/lib/rack/protection/frame_options.rb:31:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/logger.rb:15:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/common_logger.rb:33:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:231:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:224:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/method_override.rb:22:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:194:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1958:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1502:in `block in call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1729:in `synchronize'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1502:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/handler/webrick.rb:86:in `service'
	/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
	/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
	/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'`

**Comment by yegor256** [comment]
@mhurne I believe it's fixed, please try again

**Comment by mhurne** [comment]
Ok. Despite the error I was subscribed successfully the first time I attempted to subscribe. Thus, this time I got:

    Internal error at 0.0.0

    Please help us improve our service and submit the following stacktrace to our issue tracker in GitHub: yegor256/0pdd

    The email matt@thehurnes.com has already been subscribed to the list #1
	/app/mailanes.rb:458:in `block in <top (required)>'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1635:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1635:in `block in compile!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1011:in `route_eval'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1040:in `block in process_route'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1038:in `catch'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1038:in `process_route'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:990:in `block in route!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:989:in `each'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:989:in `route!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1097:in `block in dispatch!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `block in invoke'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `catch'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `invoke'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1094:in `dispatch!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:924:in `block in call!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `block in invoke'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `catch'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `invoke'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:924:in `call!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:913:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-ssl-1.4.1/lib/rack/ssl.rb:27:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.3/lib/rack/protection/xss_header.rb:18:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.3/lib/rack/protection/json_csrf.rb:26:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.3/lib/rack/protection/base.rb:50:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.3/lib/rack/protection/base.rb:50:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.3/lib/rack/protection/frame_options.rb:31:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/logger.rb:15:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/common_logger.rb:33:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:231:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:224:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/method_override.rb:22:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:194:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1958:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1502:in `block in call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1729:in `synchronize'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1502:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/handler/webrick.rb:86:in `service'
	/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
	/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
	/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'

**Comment by yegor256** [comment]
@mhurne this one is fixed too. You can try to subscribe again, there will be no error message. If you see any other issues, please don't hesitate to report.
