### ISSUE TITLE
email verification

### ISSUE THREAD

**Issue by yegor256** [yegor256/mailanes#39]
Let's make it possible to require new subscribers to verify their emails, just by adding this to the YAML of the list:

```yaml
confirmation_required: true
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.20.0`

**Comment by 0crat** [comment]
Job `gh:yegor256/mailanes#39` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
