### ISSUE TITLE
notify on delivery failures

### ISSUE THREAD

**Issue by yegor256** [yegor256/mailanes#82]
In Telegram

**Comment by yegor256** [comment]
@rultor release, tag is `0.19.6`

**Comment by yegor256** [comment]
@rultor release, tag is `0.19.6`

**Comment by yegor256** [comment]
@rultor release, tag is `0.19.6`

**Comment by yegor256** [comment]
@rultor release, tag is `0.19.6`

**Comment by 0crat** [comment]
Job `gh:yegor256/mailanes#82` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
